server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  # Docker container logs
  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          namespace: stage-una-crm-ru
          __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
      - json:
          expressions:
            stream: stream
            attrs: attrs
            tag: attrs.tag
            time: time
            level: attrs.level
            service: attrs.service
            container_name: attrs.container_name
            image_name: attrs.image_name
            log: log

      - json:
          expressions:
            level: level
            message: message
            service: service
            method: method
            url: url
            statusCode: statusCode
            responseTime: responseTime
            ip: ip
            userAgent: userAgent
            traceId: traceId
            action: action
            status: status
            error: error
            stack: stack

      - labels:
          stream:
          level:
          service:
          container_name:
          image_name:
          traceId:
          action:
          status:

      - timestamp:
          source: time
          format: RFC3339Nano

      - output:
          source: log
